Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/tracker_collectables.json")
Tracker:AddLayouts("layouts/tracker_goal.json")
Tracker:AddLayouts("layouts/tracker_unlocks.json")
Tracker:AddLayouts("layouts/tracker_keys_gems.json")
Tracker:AddLayouts("layouts/tracker_checkpoints.json")
Tracker:AddLayouts("layouts/tracker_settings.json")
Tracker:AddLayouts("layouts/broadcast.json")

Tracker:AddLayouts("layouts/tabbed_maps.json")

if Tracker.ActiveVariantUID == 'var_1_chapters' then
	Tracker:AddLayouts("layouts/0/0.json")
	Tracker:AddLayouts("layouts/0/0_a.json")

	Tracker:AddLayouts("layouts/1/1.json")
	Tracker:AddLayouts("layouts/1/1_a.json")
	Tracker:AddLayouts("layouts/1/1_b.json")
	Tracker:AddLayouts("layouts/1/1_c.json")

	Tracker:AddLayouts("layouts/2/2.json")
	Tracker:AddLayouts("layouts/2/2_a.json")
	Tracker:AddLayouts("layouts/2/2_b.json")
	Tracker:AddLayouts("layouts/2/2_c.json")

	Tracker:AddLayouts("layouts/3/3.json")
	Tracker:AddLayouts("layouts/3/3_a.json")
	Tracker:AddLayouts("layouts/3/3_b.json")
	Tracker:AddLayouts("layouts/3/3_c.json")

	Tracker:AddLayouts("layouts/4/4.json")
	Tracker:AddLayouts("layouts/4/4_a.json")
	Tracker:AddLayouts("layouts/4/4_b.json")
	Tracker:AddLayouts("layouts/4/4_c.json")

	Tracker:AddLayouts("layouts/5/5.json")
	Tracker:AddLayouts("layouts/5/5_a.json")
	Tracker:AddLayouts("layouts/5/5_b.json")
	Tracker:AddLayouts("layouts/5/5_c.json")

	Tracker:AddLayouts("layouts/6/6.json")
	Tracker:AddLayouts("layouts/6/6_a.json")
	Tracker:AddLayouts("layouts/6/6_b.json")
	Tracker:AddLayouts("layouts/6/6_c.json")

	Tracker:AddLayouts("layouts/7/7.json")
	Tracker:AddLayouts("layouts/7/7_a.json")
	Tracker:AddLayouts("layouts/7/7_b.json")
	Tracker:AddLayouts("layouts/7/7_c.json")

	Tracker:AddLayouts("layouts/8/8.json")
	Tracker:AddLayouts("layouts/8/8_a.json")

	Tracker:AddLayouts("layouts/9/9.json")
	Tracker:AddLayouts("layouts/9/9_a.json")
	Tracker:AddLayouts("layouts/9/9_b.json")
	Tracker:AddLayouts("layouts/9/9_c.json")
	
	Tracker:AddLayouts("layouts/10/10.json")
	Tracker:AddLayouts("layouts/10/10_a.json")
elseif Tracker.ActiveVariantUID == 'var_0_full' then
	Tracker:AddLayouts("layouts/0/0.json")
	Tracker:AddLayouts("layouts/0/0_a.json")
	Tracker:AddLayouts("layouts/0/0_a_0.json")

	Tracker:AddLayouts("layouts/1/1.json")
	Tracker:AddLayouts("layouts/1/1_a.json")
	Tracker:AddLayouts("layouts/1/1_a_0.json")
	Tracker:AddLayouts("layouts/1/1_a_1.json")
	Tracker:AddLayouts("layouts/1/1_a_2.json")
	Tracker:AddLayouts("layouts/1/1_b.json")
	Tracker:AddLayouts("layouts/1/1_b_0.json")
	Tracker:AddLayouts("layouts/1/1_b_1.json")
	Tracker:AddLayouts("layouts/1/1_b_2.json")
	Tracker:AddLayouts("layouts/1/1_c.json")
	Tracker:AddLayouts("layouts/1/1_c_0.json")

	Tracker:AddLayouts("layouts/2/2.json")
	Tracker:AddLayouts("layouts/2/2_a.json")
	Tracker:AddLayouts("layouts/2/2_a_0.json")
	Tracker:AddLayouts("layouts/2/2_a_1.json")
	Tracker:AddLayouts("layouts/2/2_a_2.json")
	Tracker:AddLayouts("layouts/2/2_b.json")
	Tracker:AddLayouts("layouts/2/2_b_0.json")
	Tracker:AddLayouts("layouts/2/2_b_1.json")
	Tracker:AddLayouts("layouts/2/2_b_2.json")
	Tracker:AddLayouts("layouts/2/2_c.json")
	Tracker:AddLayouts("layouts/2/2_c_0.json")

	Tracker:AddLayouts("layouts/3/3.json")
	Tracker:AddLayouts("layouts/3/3_a.json")
	Tracker:AddLayouts("layouts/3/3_a_0.json")
	Tracker:AddLayouts("layouts/3/3_a_1.json")
	Tracker:AddLayouts("layouts/3/3_a_2.json")
	Tracker:AddLayouts("layouts/3/3_a_3.json")
	Tracker:AddLayouts("layouts/3/3_b.json")
	Tracker:AddLayouts("layouts/3/3_b_0.json")
	Tracker:AddLayouts("layouts/3/3_b_1.json")
	Tracker:AddLayouts("layouts/3/3_b_2.json")
	Tracker:AddLayouts("layouts/3/3_b_3.json")
	Tracker:AddLayouts("layouts/3/3_c.json")
	Tracker:AddLayouts("layouts/3/3_c_0.json")

	Tracker:AddLayouts("layouts/4/4.json")
	Tracker:AddLayouts("layouts/4/4_a.json")
	Tracker:AddLayouts("layouts/4/4_a_0.json")
	Tracker:AddLayouts("layouts/4/4_a_1.json")
	Tracker:AddLayouts("layouts/4/4_a_2.json")
	Tracker:AddLayouts("layouts/4/4_a_3.json")
	Tracker:AddLayouts("layouts/4/4_b.json")
	Tracker:AddLayouts("layouts/4/4_b_0.json")
	Tracker:AddLayouts("layouts/4/4_b_1.json")
	Tracker:AddLayouts("layouts/4/4_b_2.json")
	Tracker:AddLayouts("layouts/4/4_b_3.json")
	Tracker:AddLayouts("layouts/4/4_c.json")
	Tracker:AddLayouts("layouts/4/4_c_0.json")

	Tracker:AddLayouts("layouts/5/5.json")
	Tracker:AddLayouts("layouts/5/5_a.json")
	Tracker:AddLayouts("layouts/5/5_a_0.json")
	Tracker:AddLayouts("layouts/5/5_a_1.json")
	Tracker:AddLayouts("layouts/5/5_a_2.json")
	Tracker:AddLayouts("layouts/5/5_a_3.json")
	Tracker:AddLayouts("layouts/5/5_a_4.json")
	Tracker:AddLayouts("layouts/5/5_b.json")
	Tracker:AddLayouts("layouts/5/5_b_0.json")
	Tracker:AddLayouts("layouts/5/5_b_1.json")
	Tracker:AddLayouts("layouts/5/5_b_2.json")
	Tracker:AddLayouts("layouts/5/5_b_3.json")
	Tracker:AddLayouts("layouts/5/5_c.json")
	Tracker:AddLayouts("layouts/5/5_c_0.json")

	Tracker:AddLayouts("layouts/6/6.json")
	Tracker:AddLayouts("layouts/6/6_a.json")
	Tracker:AddLayouts("layouts/6/6_a_0.json")
	Tracker:AddLayouts("layouts/6/6_a_1.json")
	Tracker:AddLayouts("layouts/6/6_a_2.json")
	Tracker:AddLayouts("layouts/6/6_a_3.json")
	Tracker:AddLayouts("layouts/6/6_a_4.json")
	Tracker:AddLayouts("layouts/6/6_a_5.json")
	Tracker:AddLayouts("layouts/6/6_b.json")
	Tracker:AddLayouts("layouts/6/6_b_0.json")
	Tracker:AddLayouts("layouts/6/6_b_1.json")
	Tracker:AddLayouts("layouts/6/6_b_2.json")
	Tracker:AddLayouts("layouts/6/6_b_3.json")
	Tracker:AddLayouts("layouts/6/6_c.json")
	Tracker:AddLayouts("layouts/6/6_c_0.json")

	Tracker:AddLayouts("layouts/7/7.json")
	Tracker:AddLayouts("layouts/7/7_a.json")
	Tracker:AddLayouts("layouts/7/7_a_0.json")
	Tracker:AddLayouts("layouts/7/7_a_1.json")
	Tracker:AddLayouts("layouts/7/7_a_2.json")
	Tracker:AddLayouts("layouts/7/7_a_3.json")
	Tracker:AddLayouts("layouts/7/7_a_4.json")
	Tracker:AddLayouts("layouts/7/7_a_5.json")
	Tracker:AddLayouts("layouts/7/7_a_6.json")
	Tracker:AddLayouts("layouts/7/7_b.json")
	Tracker:AddLayouts("layouts/7/7_b_0.json")
	Tracker:AddLayouts("layouts/7/7_b_1.json")
	Tracker:AddLayouts("layouts/7/7_b_2.json")
	Tracker:AddLayouts("layouts/7/7_b_3.json")
	Tracker:AddLayouts("layouts/7/7_b_4.json")
	Tracker:AddLayouts("layouts/7/7_b_5.json")
	Tracker:AddLayouts("layouts/7/7_b_6.json")
	Tracker:AddLayouts("layouts/7/7_c.json")
	Tracker:AddLayouts("layouts/7/7_c_0.json")

	Tracker:AddLayouts("layouts/8/8.json")
	Tracker:AddLayouts("layouts/8/8_a.json")
	Tracker:AddLayouts("layouts/8/8_a_0.json")

	Tracker:AddLayouts("layouts/9/9.json")
	Tracker:AddLayouts("layouts/9/9_a.json")
	Tracker:AddLayouts("layouts/9/9_a_0.json")
	Tracker:AddLayouts("layouts/9/9_a_1.json")
	Tracker:AddLayouts("layouts/9/9_a_2.json")
	Tracker:AddLayouts("layouts/9/9_a_3.json")
	Tracker:AddLayouts("layouts/9/9_b.json")
	Tracker:AddLayouts("layouts/9/9_b_0.json")
	Tracker:AddLayouts("layouts/9/9_b_1.json")
	Tracker:AddLayouts("layouts/9/9_b_2.json")
	Tracker:AddLayouts("layouts/9/9_b_3.json")
	Tracker:AddLayouts("layouts/9/9_c.json")
	Tracker:AddLayouts("layouts/9/9_c_0.json")

	Tracker:AddLayouts("layouts/10/10.json")
	Tracker:AddLayouts("layouts/10/10_a.json")
	Tracker:AddLayouts("layouts/10/10_a_0.json")
	Tracker:AddLayouts("layouts/10/10_a_1.json")
	Tracker:AddLayouts("layouts/10/10_a_2.json")
	Tracker:AddLayouts("layouts/10/10_a_3.json")
	Tracker:AddLayouts("layouts/10/10_a_4.json")
	Tracker:AddLayouts("layouts/10/10_a_5.json")
	Tracker:AddLayouts("layouts/10/10_a_6.json")
	Tracker:AddLayouts("layouts/10/10_a_7.json")
	Tracker:AddLayouts("layouts/10/10_a_8.json")
end