name: Logic Bug Report
description: File a bug report for logic.
title: "[Logic Bug]: "
labels: ["bug", "logic"]
assignees:
  - zeeveez
type: bug
body:
  - type: markdown
    attributes:
      value: |
        ## NOTE: Something which is indicated as inaccessible (red) but is in fact reachable Out of Logic (yellow) is almost certainly not a bug. Use the OOL Request form for new OOL requests.
  - type: dropdown
    id: chapter
    attributes:
      label: Chapter
      description: What chapter is the issue in?
      options:
        - Choose...
        - 0 - Prologue
        - 1 - Forsaken City
        - 2 - Old Site
        - 3 - Celestial Resort
        - 4 - Golden Ridge
        - 5 - Mirror Temple
        - 6 - Reflection
        - 7 - The Summit
        - 8 - Epilogue
        - 9 - Core
        - 10 - Farewell
      default: 0
    validations:
      required: true
  - type: input
    id: room
    attributes:
      label: Room
      description: What room is the issue in?
      placeholder: b-01 etc.
    validations:
      required: true
  - type: textarea
    id: what-issue
    attributes:
      label: What is the issue?
      description: What and why is it an issue? Is this something that is obviously inaccessible? etc.
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Tracker screenshot
      description: Upload a complete screenshot of the tracker ensuring the issue is visable, as well as all items and checkpoints.
    validations:
      required: true
  - type: checkboxes
    id: latest-version
    attributes:
      label: Latest Version
      description: Are you using the latest version of the PopTracker pack?
      options:
        - label: I am using the latest version of the PopTracker pack.
          required: true