name: Logic Addition Request
description: Request an addition to logic
title: "[Logic Addition]: "
labels: ["feature-request", "logic"]
assignees:
  - zeeveez
body:
  - type: dropdown
    id: chapter
    attributes:
      label: Chapter
      description: What chapter is the addition for?
      options:
        - 1 - Forsaken City
        - 2 - Old Site
        - 3 - Celestial Resort
        - 4 - Golden Ridge
        - 5 - Mirror Temple
        - 6 - Reflection
        - 7 - The Summit
        - 8 - Core
        - 9 - Farewell
    validations:
      required: true
  - type: dropdown
    id: side
    attributes:
      label: Side
      description: What side is the addition for (for Farewell use side A)?
      options:
        - A
        - B
        - C
    validations:
      required: true
  - type: input
    id: start-room
    attributes:
      label: Starting Room
      description: What room is the starting room (for multi-room strats, use the room first room in the sequence)?
      placeholder: e.g. b-01
    validations:
      required: true
  - type: dropdown
    id: destination-type
    attributes:
      label: Destination type
      description: What is the type of destination?
      options:
        - Room
        - Strawberry
        - Cassette
        - Crystal Heart
        - Level Clear
        - Car
        - Key
        - Gem
    validations:
      required: true
  - type: input
    id: destination
    attributes:
      label: Ending Room/Location
      description: What room or (if for example there are multiple berries) location is the destination?
      placeholder: e.g. b-02, Strawberry 2
    validations:
      required: false
  - type: textarea
    id: required-items
    attributes:
      label: What items are required?
      description: List every item required for the additional logic, if no items are required, state so.
      placeholder: e.g. kevin blocks, dash refills, coins
    validations:
      required: true
  - type: checkboxes
    id: multi-room
    attributes:
      label: Multi-Room Strat
      description: Does the logic require multi-room tech to perform?
      options:
        - label: The logic requires multi-room tech to perform
  - type: input
    id: video-link
    attributes:
      label: Logic video
      description: Unless it is self-evident, ideally provide a video link of the logic being added to prove that it's doable.
    validations:
      required: false
  - type: upload
    id: video
    attributes:
      label: Logic video
      description: Unless it is self-evident, ideally upload a video of the logic being added to prove that it's doable.
    validations:
      required: false
  - type: checkboxes
    id: latest-version
    attributes:
      label: Latest Version
      description: Are you using the latest version of the PopTracker pack?
      options:
        - label: I am using the latest version of the PopTracker pack.
          required: true