ITEM_LOCATIONS = {
	-- Item, Location, no keysanity only, no gemsanity only
	{ "celestialresorta-frontdoorkey", "Celestial Resort A - Front Door Key", true, false },
	{ "celestialresorta-hallwaykey1", "Celestial Resort A - Hallway Key 1" , true, false },
	{ "celestialresorta-hallwaykey2", "Celestial Resort A - Hallway Key 2" , true, false },
	{ "brownclutter", "Celestial Resort A - Brown Clutter" , false, false },
	{ "greenclutter", "Celestial Resort A - Green Clutter" , false, false },
	{ "pinkclutter", "Celestial Resort A - Pink Clutter" , false, false },
	{ "celestialresorta-hugemesskey", "Celestial Resort A - Huge Mess Key" , true, false },
	{ "celestialresorta-presidentialsuitekey", "Celestial Resort A - Presidential Suite Key" , true, false },
	{ "mirrortemplea-entrancekey", "Mirror Temple A - Entrance Key" , true, false },
	{ "mirrortemplea-depthskey", "Mirror Temple A - Depths Key" , true, false },
	{ "mirrortemplea-searchkey1", "Mirror Temple A - Search Key 1" , true, false },
	{ "mirrortemplea-searchkey2", "Mirror Temple A - Search Key 2" , true, false },
	{ "mirrortemplea-searchkey3", "Mirror Temple A - Search Key 3" , true, false },
	{ "mirrortempleb-centralchamberkey1", "Mirror Temple B - Central Chamber Key 1" , true, false },
	{ "mirrortempleb-centralchamberkey2", "Mirror Temple B - Central Chamber Key 2" , true, false },
	{ "thesummita-gem1", "The Summit A - Gem 1" , false, true },
	{ "thesummita-gem2", "The Summit A - Gem 2" , false, true },
	{ "thesummita-gem3", "The Summit A - Gem 3" , false, true },
	{ "thesummita-gem4", "The Summit A - Gem 4" , false, true },
	{ "thesummita-gem5", "The Summit A - Gem 5" , false, true },
	{ "thesummita-gem6", "The Summit A - Gem 6" , false, true },
	{ "thesummita-2500mkey", "The Summit A - 2500 M Key" , true, false },
	{ "farewell-powersourcekey1", "Farewell - Power Source Key 1" , true, false },
	{ "farewell-powersourcekey2", "Farewell - Power Source Key 2" , true, false },
	{ "farewell-powersourcekey3", "Farewell - Power Source Key 3" , true, false },
	{ "farewell-powersourcekey4", "Farewell - Power Source Key 4" , true, false },
	{ "farewell-powersourcekey5", "Farewell - Power Source Key 5" , true, false }
}