ITEM_LOCATIONS = {
	-- Item, Location, no keysanity only, no gemsanity only, code filter
	{ "celestialresorta-frontdoorkey", "Celestial Resort A - Front Door Key", true, false, nil },
	{ "celestialresorta-hallwaykey1", "Celestial Resort A - Hallway Key 1" , true, false, nil },
	{ "celestialresorta-hallwaykey2", "Celestial Resort A - Hallway Key 2" , true, false, nil },
	{ "brown_clutter", "Celestial Resort A - Brown Clutter" , false, false, nil },
	{ "green_clutter", "Celestial Resort A - Green Clutter" , false, false, nil },
	{ "pink_clutter", "Celestial Resort A - Pink Clutter" , false, false, nil },
	{ "celestialresorta-hugemesskey", "Celestial Resort A - Huge Mess Key" , true, false, nil },
	{ "celestialresorta-presidentialsuitekey", "Celestial Resort A - Presidential Suite Key" , true, false, nil },
	{ "mirrortemplea-entrancekey", "Mirror Temple A - Entrance Key" , true, false, nil },
	{ "mirrortemplea-depthskey", "Mirror Temple A - Depths Key" , true, false, nil },
	{ "mirrortemplea-searchkey1", "Mirror Temple A - Search Key 1" , true, false, nil },
	{ "mirrortemplea-searchkey2", "Mirror Temple A - Search Key 2" , true, false, nil },
	{ "mirrortemplea-searchkey3", "Mirror Temple A - Search Key 3" , true, false, nil },
	{ "mirrortempleb-centralchamberkey1", "Mirror Temple B - Central Chamber Key 1" , true, false, nil },
	{ "mirrortempleb-centralchamberkey2", "Mirror Temple B - Central Chamber Key 2" , true, false, nil },
	{ "thesummita-gem1", "The Summit A - Gem 1" , false, true, nil },
	{ "thesummita-gem2", "The Summit A - Gem 2" , false, true, nil },
	{ "thesummita-gem3", "The Summit A - Gem 3" , false, true, nil },
	{ "thesummita-gem4", "The Summit A - Gem 4" , false, true, nil },
	{ "thesummita-gem5", "The Summit A - Gem 5" , false, true, nil },
	{ "thesummita-gem6", "The Summit A - Gem 6" , false, true, nil },
	{ "thesummita-2500mkey", "The Summit A - 2500 M Key" , true, false, nil },
	{ "power_source_breaker", "Farewell - Power Source - Breaker Disable" , false, false, nil },
	{ "farewell-powersourcekey1", "Farewell - Power Source Key 1" , true, false, nil },
	{ "farewell-powersourcekey2", "Farewell - Power Source Key 2" , true, false, nil },
	{ "farewell-powersourcekey3", "Farewell - Power Source Key 3" , true, false, nil },
	{ "farewell-powersourcekey4", "Farewell - Power Source Key 4" , true, false, nil },
	{ "farewell-powersourcekey5", "Farewell - Power Source Key 5" , true, false, nil },
	{ "GOMODE", "The Summit A - Level Clear" , false, false, 'goal_area_the_summit_a_side' },
	{ "GOMODE", "The Summit B - Level Clear" , false, false, 'goal_area_the_summit_b_side' },
	{ "GOMODE", "The Summit C - Level Clear" , false, false, 'goal_area_the_summit_c_side' },
	{ "GOMODE", "Core A - Level Clear" , false, false, 'goal_area_core_a_side' },
	{ "GOMODE", "Core B - Level Clear" , false, false, 'goal_area_core_b_side' },
	{ "GOMODE", "Core C - Level Clear" , false, false, 'goal_area_core_c_side' },
	{ "GOMODE", "Farewell - Crystal Heart?" , false, false, 'goal_area_empty_space' },
	{ "GOMODE", "Farewell - Level Clear" , false, false, 'goal_area_farewell' },
	{ "GOMODE", "Farewell - Golden Strawberry" , false, false, 'goal_area_farewell_golden' }
}