function LoadHorizontalLayout()
	Tracker:AddLayouts("layouts/tracker/horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_bar_bottom.json")
	Tracker:AddLayouts("layouts/tracker/tracker_progress_graph/tracker_progress_graph.json")
	Tracker:AddLayouts("layouts/tracker/tracker_checkpoints/tracker_checkpoints_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_progress/tracker_progress_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_goal/tracker_goal_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_keys_gems/tracker_keys_gems_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_sanity/tracker_sanity_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_items/tracker_items_horizontal.json")
	Tracker:AddLayouts("layouts/tracker/tracker_triggers/tracker_triggers_horizontal.json")
end

function LoadVerticalLayout()
	Tracker:AddLayouts("layouts/tracker/vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_bar_left.json")
	Tracker:AddLayouts("layouts/tracker/tracker_bar_right.json")
	Tracker:AddLayouts("layouts/tracker/tracker_progress_graph/tracker_progress_graph.json")
	Tracker:AddLayouts("layouts/tracker/tracker_checkpoints/tracker_checkpoints_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_progress/tracker_progress_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_goal/tracker_goal_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_keys_gems/tracker_keys_gems_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_sanity/tracker_sanity_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_items/tracker_items_vertical.json")
	Tracker:AddLayouts("layouts/tracker/tracker_triggers/tracker_triggers_vertical.json")
end